// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfthjxoisysaglstgqbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmdGhqeG9pc3lzYWdsc3RncWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTk4NjcsImV4cCI6MjA3MTYzNTg2N30.5DxfALSyvThvwHT8I8X-gkFM989hxNsyOputmjp3iyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});